# Generated by Django 4.2.18 on 2025-04-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'personal_data',
            '0002_alter_personaldata_city_and_more'
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaldata',
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты'
            },
        ),
        migrations.AddField(
            model_name='personaldata',
            name='agreement',
            field=models.BooleanField(
                default=False,
                verbose_name='Согласие на обработку данных'
            ),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='payment_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Наличный', 'Наличный расчет'),
                    ('Ипотека', 'Ипотека'),
                    ('Рассрочка', 'Рассрочка')
                ],
                max_length=50,
                null=True,
                verbose_name='Тип оплаты'
            ),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='target',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Проживание', 'Для проживания'),
                    ('Инвестиции', 'Инвестирования'),
                    ('Аренда', 'Под сдачу')
                ],
                max_length=50,
                null=True,
                verbose_name='Цель'
            ),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='type_of_housing',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Новостройки', 'Первичное (Новостройки)'),
                    ('Вторичное', 'Вторичное')
                ],
                max_length=50,
                null=True,
                verbose_name='Тип жилья'
            ),
        ),
    ]
