# Generated by Django 3.2 on 2025-05-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0004_alter_personaldata_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Наличный расчет', 'Наличный расчет'), ('Ипотека', 'Ипотека'), ('Рассрочка', 'Рассрочка')], max_length=50, null=True, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='target',
            field=models.CharField(blank=True, choices=[('Для проживания', 'Для проживания'), ('Инвестирования', 'Инвестирования'), ('Под сдачу', 'Под сдачу')], max_length=50, null=True, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='type_of_housing',
            field=models.CharField(blank=True, choices=[('Первичное (Новостройки)', 'Первичное (Новостройки)'), ('Вторичное', 'Вторичное')], max_length=50, null=True, verbose_name='Тип жилья'),
        ),
    ]
