services:
  frontend:
    image: bestagent/bestagent-elera-frontend:latest
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - frontend_build:/app/result_build/
    environment:
      NODE_ENV: production
    restart: always

  backend:
    image: bestagent/bestagent-elera-backend:latest
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_value:/var/html/static/
    environment:
      - STATIC_ROOT=/var/html/static/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /root/PROJECT_ELERA/infra/nginx/certs:/etc/nginx/ssl:ro
      - frontend_build:/usr/share/nginx/html/
      - static_value:/var/html/backend_static/
      - ./nginx/acme-challenge:/var/www/html/.well-known/acme-challenge
    restart: always
    depends_on:
      - backend
      - frontend

volumes:
  frontend_build:
  static_value:
  media_value: