version: '3.8'

services:
  frontend:
    image: $DOCKER_HUB_USERNAME/bestagent-elera-frontend:latest
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend/build:/app/build

  backend:
    image: $DOCKER_HUB_USERNAME/bestagent-elera-backend:latest
    restart: always
    command: gunicorn --bind 0.0.0.0:8000 core.wsgi
    environment:
      - DATABASE_URL=postgres://postgre:Restart.1996@db:5432/bestagent-elera
      - SECRET_KEY=your-secret-key
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: Restart.1996
      POSTGRES_DB: bestagent-elera
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
      - ./backend/static:/var/html/static
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data: