version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.prod
    networks:
      - app-network
    restart: always

  backend:
    build:
      context: ../backend
    restart: always
    volumes:
      - static_value:/app/backend_static/
    environment:
      DATABASE_URL: postgres://postgre:Restart.1996@db:5432/bestagent-elera
      SECRET_KEY: ${DJANGO_SECRET_KEY}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: Restart.1996
      POSTGRES_DB: bestagent-elera
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/backend_static
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:
  static_value:

networks:
  app-network:
    driver: bridge