name: Bestagent-Elera Deployment Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_NAME: bestagent-elera
  DOMAIN: bestagent-elera.ru

jobs:
  tests:
    name: Run Tests and Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt
          pip install flake8  # Или другие линтеры

      - name: Run linting
        run: |
          flake8 backend/  # Проверка только бэкенда

  build_and_push_to_docker_hub:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: backend
          file: backend/Dockerfile
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.PROJECT_NAME }}-backend:latest
          push: true

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: frontend
          file: frontend/Dockerfile
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.PROJECT_NAME }}-frontend:latest
          push: true
  deploy:
  name: Deploy to Beget
  runs-on: ubuntu-latest
  needs: build_and_push_to_docker_hub
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Prepare SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "Host fabia.beget.com" >> ~/.ssh/config
        echo "  User ${{ secrets.BEGET_USERNAME }}" >> ~/.ssh/config
        echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
        chmod 600 ~/.ssh/config

    - name: Rsync files
      run: |
        rsync -avz --delete \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ ${{ secrets.BEGET_USERNAME }}@ibrokhqk.beget.com:/home/i/ibrokhqk/bestagent-elera.ru/public_html/PROJECT_ELERA/

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1
      with:
        host: fabia.beget.com
        username: ${{ secrets.BEGET_USERNAME }}
        password: ${{ secrets.BEGET_PASSWORD }}
        script: |
          cd /home/i/ibrokhqk/bestagent-elera.ru/public_html/PROJECT_ELERA/infra/
          docker-compose down
          docker-compose pull
          docker-compose up -d --build
          docker-compose exec backend python manage.py migrate
          docker-compose exec backend python manage.py collectstatic --noinput
            