name: Bestagent-Elera Deployment Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_NAME: bestagent-elera
  DOMAIN: bestagent-elera.ru

jobs:
  tests:
    name: Run Tests and Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt
          pip install flake8  # Или другие линтеры

      - name: Run linting
        run: |
          flake8 backend/  # Проверка только бэкенда

  build_and_push_to_docker_hub:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: backend
          file: backend/Dockerfile
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.PROJECT_NAME }}-backend:latest
          push: true

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: frontend
          file: frontend/Dockerfile
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.PROJECT_NAME }}-frontend:latest
          push: true

  deploy:
    name: Deploy to Beget
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.BEGET_HOST }}  # Например, ssh.beget.com
          username: ${{ secrets.BEGET_USERNAME }}  # Ваш логин Beget
          password: ${{ secrets.BEGET_PASSWORD }}
          script: |
            set -e
            echo "=== Starting deployment ==="
            cd dali-khinkali/
            
            echo "=== Cleaning Docker environment ==="
            sudo docker-compose down -v || true
            sudo docker system prune -a -f
            
            echo "=== Pulling new images ==="
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/bestagent-elera-backend
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/bestagent-elera-frontend
            
            echo "=== Starting containers with rebuild ==="
            sudo docker-compose up -d --build
            
            echo "=== Waiting for containers to start ==="
            sleep 15
            
            echo "=== Applying database migrations ==="
            sudo docker-compose exec -T backend python manage.py makemigrations
            sudo docker-compose exec -T backend python manage.py migrate --noinput
            
            echo "=== Collecting static files ==="
            sudo docker-compose exec -T backend python manage.py collectstatic --no-input --clear
            
            echo "=== Deployment completed successfully ==="
            sudo docker ps