name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BEGET_HOST }}
          username: ${{ secrets.BEGET_USERNAME }}
          password: ${{ secrets.BEGET_PASSWORD }}
          script: |
            # 1. Обновляем код (форсированно)
            cd /var/www/PROJECT_ELERA
            git fetch --all
            git merge origin/main
            pm2 delete frontend

            # 3. Фронтенд (установка + сборка)
            cd /var/www/PROJECT_ELERA/frontend
            npm run build
            
            # 4. Перезапуск сервисов
            pm2 serve /var/www/PROJECT_ELERA/frontend/build 3000 --name "frontend" --spa
            pm2 save
            
            echo "✅ Деплой завершен за $(($SECONDS/60))m$(($SECONDS%60))s"