name: Bestagent-Elera Deployment Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_NAME: bestagent-elera
  DOMAIN: bestagent-elera.ru

jobs:
  tests:
    name: Run Tests and Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt
          pip install flake8  # Или другие линтеры

      - name: Run linting
        run: |
          flake8 backend/  # Проверка только бэкенда

  build_and_push_to_docker_hub:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: backend
          file: backend/Dockerfile
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.PROJECT_NAME }}-backend:latest
          push: true

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: frontend
          file: frontend/Dockerfile
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.PROJECT_NAME }}-frontend:latest
          push: true
  deploy:
    name: Deploy to Production
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deployment
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.BEGET_HOST }}
          username: ${{ secrets.BEGET_USERNAME }}
          key: ${{ secrets.BEGET_SSH_KEY }}
          script: |
            set -e
            echo "=== Starting deployment ==="
            cd $COMPOSE_DIR
            
            echo "=== Pulling new images ==="
            docker-compose pull
            
            echo "=== Stopping old containers ==="
            docker-compose down
            
            echo "=== Cleaning old images ==="
            docker image prune -a -f --filter "until=24h"
            
            echo "=== Starting new containers ==="
            docker-compose up -d --build
            
            echo "=== Waiting for services to start (30s) ==="
            sleep 30
            
            echo "=== Applying database migrations ==="
            docker-compose exec -T backend python manage.py migrate --noinput
            
            echo "=== Collecting static files ==="
            docker-compose exec -T backend python manage.py collectstatic --noinput --clear
            
            echo "=== Checking services health ==="
            docker ps
            curl -I localhost || true
            
            echo "✓ Deployment successful! 🚀"
              